packages:
  - 'react'
  - 'core'
  - 'testServer'
  - 'cli'
  - 'examples/*'
  - 'react-plugin-vite'
  - 'react-plugin-rsbuild'
  - 'react-plugin-rspack'
  - 'react-plugin-next'
  - 'builder/visionOS'
  - 'ciTest'
  - 'shared'

