// Generated by tools/scripts/generate-runtime-capability-manifest.js.
// Edit packages/visionOS/runtime-capabilities.json, then regenerate this file.

import Foundation
@preconcurrency import WebKit

enum RuntimeCapabilityManifestProvider {
    static let manifestVersion = 1
    static let runtimeType = "visionos"
    static let supported = [
        "-xr-back",
        "-xr-background-material",
        "-xr-depth",
        "-xr-transform",
        "AttachmentAsset",
        "AttachmentEntity",
        "BoxEntity",
        "ConeEntity",
        "CylinderEntity",
        "Entity",
        "Material",
        "Material:unlit",
        "Model",
        "Model:autoplay",
        "Model:currentSrc",
        "Model:currentTime",
        "Model:duration",
        "Model:entityTransform",
        "Model:loading",
        "Model:loop",
        "Model:pause",
        "Model:paused",
        "Model:play",
        "Model:playbackRate",
        "Model:poster",
        "Model:ready",
        "Model:source",
        "ModelAsset",
        "ModelEntity",
        "PlaneEntity",
        "Reality",
        "SceneGraph",
        "SpatialDragEndEvent",
        "SpatialDragEvent",
        "SpatialDragStartEvent",
        "SpatialMagnifyEndEvent",
        "SpatialMagnifyEvent",
        "SpatialRotateEndEvent",
        "SpatialRotateEvent",
        "SpatialRotateEvent:constrainedToAxis",
        "SpatialTapEvent",
        "SphereEntity",
        "UnlitMaterial",
        "VolumeScene",
        "VolumeScene:baseplateVisibility",
        "VolumeScene:defaultSize",
        "VolumeScene:resizability",
        "VolumeScene:worldAlignment",
        "VolumeScene:worldScaling",
        "WindowScene",
        "WindowScene:defaultSize",
        "WindowScene:resizability",
        "convertCoordinate",
        "initScene",
        "useAnimation",
        "useAnimation:entity",
        "useMetrics",
        "xrClientDepth",
        "xrInnerDepth",
        "xrOffsetBack",
        "xrOuterDepth",
    ]

    static func manifestDictionary() -> [String: Any] {
        return [
            "manifestVersion": manifestVersion,
            "runtime": [
                "type": runtimeType,
                "version": pwaManager.getShellVersion(),
                "buildId": pwaManager.getRuntimeBuildId(),
            ],
            "supported": supported,
        ]
    }

    static func injectionSource() -> String {
        let data = try! JSONSerialization.data(
            withJSONObject: manifestDictionary(),
            options: [.sortedKeys]
        )
        let json = String(decoding: data, as: UTF8.self)
        return """
        (() => {
          const manifest = \(json);
          Object.freeze(manifest.runtime);
          Object.freeze(manifest.supported);
          Object.freeze(manifest);
          Object.defineProperty(globalThis, "__webspatialCapabilities", {
            value: manifest,
            writable: false,
            configurable: false,
          });
        })();
        """
    }

    static func makeUserScript() -> WKUserScript {
        return WKUserScript(
            source: injectionSource(),
            injectionTime: .atDocumentStart,
            forMainFrameOnly: false
        )
    }
}
