import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import typedocSidebarCore from './docs/api-core/typedoc-sidebar';
import typedocSidebarReact from './docs/api-react/typedoc-sidebar';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],

  apiSidebar: [
    {
      type: 'category',
      label: 'core-sdk',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api-core/index',
          label: 'API Overview',
        },
        {
          type: 'doc',
          id: 'api-core/globals',
          label: 'Globals',
        },
        {
          type: 'category',
          label: 'Classes',
          link: {type: 'doc', id: 'api-core-classes-index'},
          items: typedocSidebarCore.items[0].items, // autogenerated Typedoc classes :contentReference[oaicite:2]{index=2}
        },
        {
          type: 'category',
          label: 'Interfaces',
          link: {type: 'doc', id: 'api-core-interfaces-index'},
          items: typedocSidebarCore.items[1].items,
        },
        {
          type: 'category',
          label: 'Type Alias',
          link: {type: 'doc', id: 'api-core-type-aliases-index'},
          items: typedocSidebarCore.items[2].items,
        },
      ],
    },
    {
      type: 'category',
      label: 'react-sdk',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api-react/index',
          label: 'API Overview',
        },
        // {
        //   type: 'doc',
        //   id: 'api-react/globals',
        //   label: 'Globals',
        // },
        {
          type: 'category',
          label: 'Classes',
          link: {type: 'doc', id: 'api-react-classes-index'},
          items: typedocSidebarReact.items[0].items, // autogenerated Typedoc classes :contentReference[oaicite:2]{index=2}
        },
        {
          type: 'category',
          label: 'Interfaces',
          link: {type: 'doc', id: 'api-react-interfaces-index'},
          items: typedocSidebarReact.items[1].items,
        },
        {
          type: 'category',
          label: 'Type Alias',
          link: {type: 'doc', id: 'api-react-type-aliases-index'},
          items: typedocSidebarReact.items[2].items,
        },
        {
          type: 'category',
          label: 'Variables',
          link: {type: 'doc', id: 'api-react-variables-index'},
          items: typedocSidebarReact.items[3].items,
        },
        {
          type: 'category',
          label: 'Functions',
          link: {type: 'doc', id: 'api-react-functions-index'},
          items: typedocSidebarReact.items[4].items,
        },
      ],
    },
  ],
};

export default sidebars;
