# Used to merge main/stable branches with each other
name: PR Auto Merge Bot

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  pr-check-ci:
    if: github.repository == 'webspatial/webspatial-sdk'
    permissions:
      checks: read # for actions-cool/check-pr-ci to get check reference
      contents: write # for actions-cool/check-pr-ci to merge PRs
      issues: write # for actions-cool/check-pr-ci to update issues
      pull-requests: write # for actions-cool/check-pr-ci to update PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-pr-ci@v1
        with:
          filter-label: BranchAutoMerge
          filter-creator-authority: write
          filter-head-ref: 'main, stable, stable-merge-main'
          filter-support-fork: false
          skip-run-names: 'pr-check-ci'
          conflict-review-body: 😅 This branch has conflicts that must be resolved!
          success-review: true
          success-merge: true
          merge-method: merge
          merge-title: 'chore: auto merge branches (#${number})'
